name:                echoBot-v3
version:             0.1.0.0
github:              "githubuser/echoBot-v3"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/echoBot-v3#readme>

dependencies:
- base >= 4.7 && < 5
- configurator
- text
- http-conduit
- bytestring
- utf8-string
- aeson
- vector
- containers 
- hspec
- time

library:
  source-dirs: src

executables:
  echoBot-v3-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echoBot-v3

tests:
  echoBot-v3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - echoBot-v3
